Test

diff --git a/.github/workflows/signBinaries.yml b/.github/workflows/signBinaries.yml
--- a/.github/workflows/signBinaries.yml
+++ b/.github/workflows/signBinaries.yml
@@ -18,8 +18,20 @@ jobs:
       - name: Build
         run: go build -v .
 
-      - name: Debug
-        run: env | grep APPLE
+      - name: Check Secrets
+        run: |
+          if [[ -z "${{ secrets.APPLE_CERT_DATA }}" ]]; then
+            echo "Error: Missing APPLE_CERT_DATA secret."
+            exit 1
+          fi
+          if [[ -z "${{ secrets.APPLE_CERT_PASSWORD }}" ]]; then
+            echo "Error: Missing APPLE_CERT_PASSWORD secret."
+            exit 1
+          fi
+          if [[ -z "${{ secrets.APPLE_TEAM_ID }}" ]]; then
+            echo "Error: Missing APPLE_TEAM_ID secret."
+            exit 1
+          fi
 
       - name: Sign Binary
         run: ./signscript.sh ${{ secrets.APPLE_CERT_DATA }} ${{ secrets.APPLE_CERT_PASSWORD }} ${{ secrets.APPLE_TEAM_ID }}
